// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XepNJ_1axFt8k9G-C8aAyhAroF9YtG0',
    appId: '1:32841765040:web:2b92cfe190217ccbdc6b75',
    messagingSenderId: '32841765040',
    projectId: 'bizipac-6bb00',
    authDomain: 'bizipac-6bb00.firebaseapp.com',
    storageBucket: 'bizipac-6bb00.firebasestorage.app',
    measurementId: 'G-383JP038YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-FMcDEPuYMHHHxiXn0OdMu-nKyC2HZpE',
    appId: '1:32841765040:android:c23913935e2a4a6edc6b75',
    messagingSenderId: '32841765040',
    projectId: 'bizipac-6bb00',
    storageBucket: 'bizipac-6bb00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1Veb87oq8cfFCnnm0ntaUPA-fE7s3Xs',
    appId: '1:32841765040:ios:4dd6ca130314afb3dc6b75',
    messagingSenderId: '32841765040',
    projectId: 'bizipac-6bb00',
    storageBucket: 'bizipac-6bb00.firebasestorage.app',
    iosBundleId: 'com.example.fmsSoftware',
  );
}
